// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicRecognitionApp.Infrastructure.Data.Contexts;

#nullable disable

namespace MusicRecognitionApp.Infrastructure.Migrations
{
    [DbContext(typeof(MusicRecognitionContext))]
    partial class MusicRecognitionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicRecognitionApp.Infrastructure.Data.Entities.AudioHashEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hash")
                        .HasColumnType("INT");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<double>("TimeOffset")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Hash" }, "IX_AudioHashes_Hash");

                    b.HasIndex(new[] { "SongId" }, "IX_AudioHashes_SongId");

                    b.ToTable("AudioHashes", (string)null);
                });

            modelBuilder.Entity("MusicRecognitionApp.Infrastructure.Data.Entities.RecognizedSongEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Matches")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecognitionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RecognitionDate" }, "IX_RecognizedSongs_RecognitionDate");

                    b.HasIndex(new[] { "SongId" }, "IX_RecognizedSongs_SongId");

                    b.ToTable("RecognizedSongs", (string)null);
                });

            modelBuilder.Entity("MusicRecognitionApp.Infrastructure.Data.Entities.SongEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Title", "Artist" }, "IX_Songs_Title_Artist")
                        .IsUnique();

                    b.ToTable("Songs", (string)null);
                });

            modelBuilder.Entity("MusicRecognitionApp.Infrastructure.Data.Entities.AudioHashEntity", b =>
                {
                    b.HasOne("MusicRecognitionApp.Infrastructure.Data.Entities.SongEntity", "Song")
                        .WithMany("AudioHashes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicRecognitionApp.Infrastructure.Data.Entities.RecognizedSongEntity", b =>
                {
                    b.HasOne("MusicRecognitionApp.Infrastructure.Data.Entities.SongEntity", "Song")
                        .WithMany("RecognizedSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicRecognitionApp.Infrastructure.Data.Entities.SongEntity", b =>
                {
                    b.Navigation("AudioHashes");

                    b.Navigation("RecognizedSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
